
services:
  backup_service:
    build: ./backup_service
    container_name: password_backup_container
    ports:
      - "5001:5001"
    volumes:
      - ..:/password_manager
    restart: always

  checker_service:
    build: ./checker_service
    container_name: password_checker_container
    ports:
      - "5002:5002"
    volumes:
      - ..:/password_manager
    restart: always