version: '3.8'

services:
  backup_service:
    image: backup_service:latest
    volumes:
      - ../../password_manager:/password_manager
    networks:
      - swarm_network
    deploy:
      replicas: 2


  checker_service:
    image: checker_service:latest
    volumes:
      - ../../password_manager:/password_manager
    networks:
      - swarm_network
    deploy:
      replicas: 2


  nginx_service:
    build: ./nginx
    image: nginx_swarm:latest
    ports:
      - "80:80"
    networks:
      - swarm_network

networks:
  swarm_network:
    driver: overlay