resolver 127.0.0.11 valid=10s;

upstream backup_servers {
    server tasks.pass_manager_backup_service:5001;
}

upstream checker_servers {
    server tasks.pass_manager_checker_service:5002;
}

server {

    listen 80;

    location /backup {
    proxy_pass http://backup_servers/;
    }

    location / {
        proxy_pass http://checker_servers;
    }
}