name: C++ Code Analysis

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 1: Добавляем MSBuild в PATH (необходимо для сборки в Windows)
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      # Шаг 2: Устанавливаем Cppcheck через Chocolatey (пакетный менеджер Windows)
      - name: Install Cppcheck
        run: |
          choco install cppcheck -y

      # Шаг 3: Запускаем статический анализ Cppcheck
      # Анализируем все файлы .cpp и .h, сохраняем результат в cppcheck.txt
      # "|| exit 0" гарантирует, что воркфлоу не упадет, если будут найдены предупреждения (аналог "|| true")
      - name: Run Cppcheck Analysis
        # Переключаем шаг на использование bash, чтобы работала конструкция "|| true"
        shell: bash
        run: |
          # Указываем точный путь к библиотекам, чтобы обойти баг с std.cfg
          cppcheck --enable=all --inconclusive --data-dir="C:/Program Files/Cppcheck/cfg" . --output-file=cppcheck.txt || true

      # Шаг 4: Сборка проекта (опционально, но полезно для C++)
      # Замени 'YourSolution.sln' на имя твоего файла решения (Solution)
      - name: Build Project
        run: |
          msbuild password_manager/password_manager.vcxproj /p:Configuration=Release /p:PlatformToolset=v143

      # Шаг 5: Загрузка артефакта с отчетом анализа
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # <-- Исправлено здесь!
        with:
          name: cppcheck-report
          path: cppcheck.txt
